eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://eureka:8761/eureka/
server:
  port: 65532
#  port: 9999
spring:
  application:
    name: service-hi